# TamiRNA Data

## Raw Count Data (long format) - ALL_SA~1.csv

**1. Description**
Table produced by tamiRNA containing read counts for all miRNAs from all samples.

**2. Findings**
1. []

**3. Contents**
- **col1** = mircoRNA
- **col2** = condition and replicate number
- **col3** = raw read count
- **col4** = in-house tamiRNA file storage location
- **col5** = sequencing ID

In [8]:
library(readr)
ALL_SA_1 <- read_csv("/Users/christopherjanschke/GIT/L4137_HBEC_EV_Transcriptomics-Project/data/01_Protease/raw_data/ALL_SA~1.CSV", show_col_types = FALSE)
head(ALL_SA_1)

  mirna         customerID              count storage_folder
1 hsa-let-7a-3p 0_005_ug_mL_Protease_1  14    NGS-153
2 hsa-let-7a-3p 0_005_ug_mL_Protease_14  8    NGS-153
3 hsa-let-7a-3p 0_08_ug_mL_Protease_13   3    NGS-153
4 hsa-let-7a-3p 2_ug_mL_Protease_2      17    NGS-153
5 hsa-let-7a-3p 2_ug_mL_Protease_5       2    NGS-153
6 hsa-let-7a-3p 24_ug_mL_Protease_10     8    NGS-153
  sequencing_sample_id
1 NGS-110-029_S29_R1_001
2 NGS-110-011_S11_R1_001
3 NGS-110-012_S12_R1_001
4 NGS-110-004_S4_R1_001
5 NGS-110-026_S26_R1_001
6 NGS-110-030_S30_R1_001

## Normalised miRNA counts - Project_1_miRNAs_Table.xlsx

**1. Description**
- Table supplied by GH containing all miRNA read counts, normalised using RPM (1 million reads). 
- 610 miRNAs detected
- miRNA nomenclature:
**hsa-let-7a-3p**
has = homo sapiens 
let-7 = microRNA family 
a = specific subtype
3p = 3 prime
- Three replicates in each condition to enable statistical analysis
 

**N.B. Normalised read counts (using RPM/CPM/RPKM etc.) are unsuitable for DGEA because DESeq2 and other software perform their own normalisation based on raw read counts. Normalised count data is mainly used for visualisation.**

**2. Findings**
1. []

**3. Contents**
- **col1** = mircoRNA
- **col2-4** = PBS control normalised read counts
- **col5-7** = 0_005_ug_mL_Protease normalised read counts
- **co8-10** = 0_08_ug_mL_Protease normalised read counts
- **col11-13** = 2_ug_mL_Protease normalised read counts
- **col14-16** = 24_ug_mL_Protease normalised read counts

In [14]:
library(readxl)
miRNAs <- read_excel('/Users/christopherjanschke/GIT/L4137_HBEC_EV_Transcriptomics-Project/data/01_Protease/raw_data/Project_1_miRNAs_Table.xlsx', col_names = F)
head(miRNAs[-1:-3,])

New names:
• `` -> `...1`
• `` -> `...2`
• `` -> `...3`
• `` -> `...4`
• `` -> `...5`
• `` -> `...6`
• `` -> `...7`
• `` -> `...8`
• `` -> `...9`
• `` -> `...10`
• `` -> `...11`
• `` -> `...12`
• `` -> `...13`
• `` -> `...14`
• `` -> `...15`
• `` -> `...16`

  ...1          ...2        ...3   ...4   ...5                 ...6   ...7
1 Condition     PBS control NA     NA     0_005_ug_mL_Protease NA     NA
2 Replicate no. 1           2      3      1                    2      3
3 hsa-let-7a-3p 865.11      407.6  364.66 565.22               0      58.99
4 hsa-let-7a-5p 0           896.71 182.33 444.1                0      162.21
5 hsa-let-7b-3p 0           0      0      0                    0      0
6 hsa-let-7b-5p 370.76      652.16 729.33 444.1                343.52 729.95
  ...8                ...9   ...10 ...11            ...12              ...13
1 0_08_ug_mL_Protease NA     NA    2_ug_mL_Protease NA                 NA
2 1                   2      3     1                2                  3
3 106.38              0      0     451.43           64.239999999999995 0
4 319.14              195.19 69.3  26.55            449.68             208.81
5 0                   0      0     0                0                  0
6 496.44              1409.7 438.9 1832.28          1477.53            1740.1
  ...14             ...15   ...16
1 24_ug_mL_Protease NA      NA
2 1                 2       3
3 149.22            211.55  98.91
4 55.96             231.7   395.65
5 0                 10.07   0
6 1417.59           1631.98 1153.97

## Raw Count Data (wide format) - raw_miRNAs_(protease_data).xlsx

**1. Description**
- Table produced by tamiRNA containing raw read counts for all miRNAs from all samples.
- This includes conditions and replicates but not sequencing ID.

**2. Findings**
1. []

**3. Contents**
- **col1** = mircoRNA
- **col2-4** = PBS control raw read counts
- **col5-7** = 0_005_ug_mL_Protease raw read counts
- **co8-10** = 0_08_ug_mL_Protease raw read counts
- **col11-13** = 2_ug_mL_Protease raw read counts
- **col14-16** = 24_ug_mL_Protease raw read counts

In [21]:
library(readr)
raw_miRNAs <- read_excel("/Users/christopherjanschke/GIT/L4137_HBEC_EV_Transcriptomics-Project/data/01_Protease/raw_data/raw_miRNAs_(protease_data).xlsx",col_names = FALSE)
head(raw_miRNAs[-1:-2,])

New names:
• `` -> `...1`
• `` -> `...2`
• `` -> `...3`
• `` -> `...4`
• `` -> `...5`
• `` -> `...6`
• `` -> `...7`
• `` -> `...8`
• `` -> `...9`
• `` -> `...10`
• `` -> `...11`
• `` -> `...12`
• `` -> `...13`
• `` -> `...14`
• `` -> `...15`
• `` -> `...16`

  ...1          ...2 ...3 ...4 ...5  ...6 ...7 ...8 ...9 ...10 ...11 ...12
1 Condition     PBS  NA   NA   0.005 NA    NA  0.08 NA   NA     2    NA
2 hsa-let-7a-3p 14    5    4   14     0     8  3     0    0    17     2
3 hsa-let-7a-5p 0    11    2   11     0    22  9     9    3     1    14
4 hsa-let-7b-3p 0     0    0   0      0     0  0     0    0     0     0
5 hsa-let-7b-5p 6     8    8   11     8    99  14   65   19    69    46
6 hsa-let-7c-5p 18   32    2   24    21   105  4    21    3    12    14
  ...13 ...14 ...15 ...16
1 NA    24     NA   NA
2  0     8     21    6
3  6     3     23   24
4  0     0      1    0
5 50    76    162   70
6 46    35     37   22

## Read Type Classifications - readsClassificationTable.xlsx

**1. Description**
- Table produced by tamiRNA containing the different types of RNAs produced from sequencing

**2. Findings**
1. []

**3. Contents**
- **col1** = condition and replicate
- **col2** = treated/control
- **col3-12** = (from left to right) microRNA, transfer RNA, PIWI-interacting RNA, ribosomal RNA, long non-coding RNA, messenger RNA, small nucelar RNA, small nucleolar RNA, yRNA, small cytoplasmic RNA
- **col13** = in-house tamiRNA spike-in RNA molecule used to count absolute counts
- **col14** = in-house tamiRNA spike-in RNA molecule used for extra calibration
- **col15** = reads mapped to different types of RNAs, not defined in table 
- **col16** = reads mapped to genome but not assigned to a known RNA category
- **col17** = reads that could not be aligned to the reference genome

In [22]:
library(readr)
conditions <- read_excel("/Users/christopherjanschke/GIT/L4137_HBEC_EV_Transcriptomics-Project/data/01_Protease/raw_data/readsClassificationTable.xlsx", col_names = FALSE)
head(conditions[-1,])

New names:
• `` -> `...1`
• `` -> `...2`
• `` -> `...3`
• `` -> `...4`
• `` -> `...5`
• `` -> `...6`
• `` -> `...7`
• `` -> `...8`
• `` -> `...9`
• `` -> `...10`
• `` -> `...11`
• `` -> `...12`
• `` -> `...13`
• `` -> `...14`
• `` -> `...15`
• `` -> `...16`
• `` -> `...17`

  ...1                    ...2    ...3   ...4   ...5  ...6    ...7   ...8
1 customerID              Group   miRNA  tRNA   piRNA rRNA    lncRNA mRNA
2 0_005_ug_mL_Protease_1  Treated 24923  33856  9366  547934  28447  19862
3 0_005_ug_mL_Protease_11 Treated 23797  22136  13492 708800  40614  27147
4 0_005_ug_mL_Protease_14 Treated 135958 156494 12497 1137492 47629  27341
5 0_08_ug_mL_Protease_13  Treated 29732  112104 14810 729986  39130  25610
6 0_08_ug_mL_Protease_8   Treated 46597  44233  11708 710277  45989  27760
  ...9  ...10  ...11 ...12 ...13           ...14
1 snRNA snoRNA yRNA  scRNA RNA QC spike-in spike-in calibrator
2 559   681    671   1     45812           19493
3 2191  696    560   6     59036           28225
4 17049 1614   2371  42    44098           26948
5 36999 1189   2051  52    51184           23903
6 3908  841    1402  11    73933           30270
  ...15             ...16                ...17
1 other RNA species unclassified genomic unmapped
2 88377             1073089              6352056
3 231677            1456557              6380974
4 278422            1370925              5887094
5 230118            1331052              6031365
6 220144            1546610              6494183

# Raw Data

## Sample Metadata

In [10]:
library(readr)
X01_sample_metadata <- read_csv("/Users/christopherjanschke/GIT/L4137_HBEC_EV_Transcriptomics-Project/01_Protease/results/tables/01_sample_metadata.csv", show_col_types = FALSE)
X01_sample_metadata

   Condition               Treatment Replicate Sequencing ID          File Size
1  PBS_03                  Untreated 1         NGS-110-028_S28_R1_001 354M
2  PBS_04                  Untreated 2         NGS-110-016_S16_R1_001 374M
3  PBS_06                  Untreated 3         NGS-110-007_S7_R1_001  282M
4  0_005_ug_mL_Protease_01 Treated   1         NGS-110-029_S29_R1_001 318M
5  0_005_ug_mL_Protease_11 Treated   2         NGS-110-017_S17_R1_001 365M
6  0_005_ug_mL_Protease_14 Treated   3         NGS-110-011_S11_R1_001 373M
7  0_08_ug_mL_Protease_13  Treated   1         NGS-110-012_S12_R1_001 371M
8  0_08_ug_mL_Protease_08  Treated   2         NGS-110-025_S25_R1_001 397M
9  0_08_ug_mL_Protease_09  Treated   3         NGS-110-006_S6_R1_001  314M
10 2_ug_mL_Protease_02     Treated   1         NGS-110-004_S4_R1_001  383M
11 2_ug_mL_Protease_05     Treated   2         NGS-110-026_S26_R1_001 405M
12 2_ug_mL_Protease_07     Treated   3         NGS-110-003_S3_R1_001  355M
13 24_ug_mL_Protease_10    Treated   1         NGS-110-030_S30_R1_001 360M
14 24_ug_mL_Protease_12    Treated   2         NGS-110-019_S19_R1_001 373M
15 24_ug_mL_Protease_15    Treated   3         NGS-110-008_S8_R1_001  348M

# Project Plan

## Methods

### Background Research

This section reviews recent papers that have performed similar analyses to establish miRNA bioinformatic workflows.

#### <u>Paper 1</u> (2025)

**Title:** A Verified Workflow for MiRNA-Seq Data Processing and Bioinformatics Analysis Using

**Date:** October 2025

**Link**: [here](https://www.jove.com/t/68760/a-verified-workflow-for-mirna-seq-data-processing-bioinformatics)

**Methods:**

##### 1. Preprocess raw reads and perform quality control

- Cutadapt
- fastp
- FastQC

##### 2. Map reads and generate count matrices

**Alignment**
- Align to reference genome
- miRBase (align to mature miRNA sequences)
- Bowtie
1. `-v 0` = no mistakes in entire read
2. `-a --best --strata` = throw away any alignment that had more mismatches than the best

**Counts**
- featureCounts
- HTSeq-count

##### 3. Perform Differential Expression Analysis in R
- DESeq2
1. `dds <- DESeq(dds)` = normalise data
2. `vsd <- vst(dds, blind=FALSE)` = variance-stabilising transformation
- EnhancedVolcano (package)

##### 4. Predict target genes of miRNAs
**Query databases** 
- TargetScan
- miRDB
- miRTarBase

**Automated Prediction**
- multiMiR (package)


##### 5. Conduct functional enrichment analysis
**GO Enrichment**
- clusterProfiler (package)
- org.Hs.eg.db (package)

**KEGG Pathway Enrichment**
- ekegg

##### 6. Construct and visualize miRNA - mRNA interaction network
- Cytoscape


**N.B. Paper includes more in-depth detail on processing steps and parameters, and includes example commands**

**Notes**
- Insert size = 18-30nt for miRNAs